apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "forest.fullname" . }}-ca-certs'
  labels:
    {{- include "forest.labels" . | nindent 4 }}
data:
  ca.pem: {{ .Values.certs.caPem | b64enc }}
  ca-key.pem: {{ .Values.certs.caKeyPem | b64enc }}
